### PR TITLE
Don't skip lines on code fence boundaries

### LINKED ISSUE #11: First line of code fence is incorrectly parsed as header for purposes of coherence
In 5.0.0, the first line of a code fence is being parsed for purposes of header coherence. This results in a `TocDoesNotRenderAsCoherentList` error when using the api, and a truncated TOC when using the CLI.

API:
~~~
[INFO] Generating table of contents for /mnt/infrastructure/docs/ingressroute.md
Traceback (most recent call last):
  File "src/generate.py", line 325, in <module>
    main()
  File "src/generate.py", line 321, in main
    _generate_table_of_contents()
  File "src/generate.py", line 230, in _generate_table_of_contents
    index[filename] = md_toc.build_toc(filename, keep_header_levels=6, parser='github')
  File "/usr/local/lib/python3.7/site-packages/md_toc/api.py", line 213, in build_toc
    raise TocDoesNotRenderAsCoherentList
md_toc.exceptions.TocDoesNotRenderAsCoherentList
~~~

CLI, with minimal test case:
~~~
[dharmab@n7 md-toc]$ cat test1.md 
# Foo1

## Foo2

### Foo3

```
#!/bin/bash
code
```

### Foo4
[dharmab@n7 md-toc]$ md_toc test1.md github
- [Foo1](#foo1)
  - [Foo2](#foo2)
    - [Foo3](#foo3)
[dharmab@n7 md-toc]$ cat test2.md 
# Foo1

## Foo2

### Foo3

```
code
#!/bin/bash
code
```

### Foo4
[dharmab@n7 md-toc]$ md_toc test2.md github
- [Foo1](#foo1)
  - [Foo2](#foo2)
    - [Foo3](#foo3)
    - [Foo4](#foo4)
~~~

### PR DESCRIPTION
**Pull request by dharmab**
Fixes #11 (?).

Any suggestions on how to unit test this?

### CODE REVIEW

**Comment by frnmst** [comment]
> Any suggestions on how to unit test this?

Maybe we need to use temporary files or mocks for `build_toc`: test different toy files that go through
all possible conditions in the function.

**Comment by dharmab** [comment]
Yeah, there could be a `test/resources` or similar directory that contains various Markdown documents, and a test module containing tests that load one or more documents and tests them end to end.

If you framework out the tests I can contribute some stress cases.

**Comment by frnmst** [comment]
I did some research but I couldn't find any best practice. I  think that the tests should be run within the `test_build_toc` function and, as you said, the markdown dummy files loaded separately. The expected outputs should also be loaded from files and loaded as strings so they can be compared with `build_toc`.

Maybe it would be better to check how other python projects solved the problem before going on:
- https://github.com/jmcgeheeiv/pyfakefs/tree/master/pyfakefs/tests
- https://github.com/kennethreitz/requests/tree/master/tests
- etc...

**Comment by frnmst** [comment]
Before thinking about these new unit tests, I have included your fix in version 5.0.1.

**Pull request merged**
